### ISSUE TITLE
Getting a mismatch trace_id

### ISSUE THREAD

**Issue by rezmuh** [davidB/tracing-opentelemetry-instrumentation-sdk#94] opened 2023-09-18 09:18 UTC
Hi, I was following the example from https://raw.githubusercontent.com/davidB/tracing-opentelemetry-instrumentation-sdk/main/examples/axum-otlp/src/main.rs to integrate axum + tracing + opentelemetry. However, I noticed that the trace_id is different between the one in HTTP header vs `find_current_trace_id()`. In the README of the example, it showed that the trace_ids were the same.

This resulted in Jaeger showing two different requests and their spans are not part of one another. Here's the screenshot
<img width="719" alt="Screenshot 2023-09-18 at 4 15 52 PM" src="https://github.com/davidB/tracing-opentelemetry-instrumentation-sdk/assets/1204244/1e6339d2-d36a-4df8-a6ef-5da5955263d9">

In Jaeger, it ended up showing like this:
<img width="1084" alt="Screenshot 2023-09-18 at 4 17 08 PM" src="https://github.com/davidB/tracing-opentelemetry-instrumentation-sdk/assets/1204244/c97b5bee-8acf-4617-85eb-ef0dccc9afd6">

Also as a reference, this is my `Cargo.toml` file:

```
[package]
name = "temp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.20"
axum-tracing-opentelemetry = "0.13.1"
init-tracing-opentelemetry = { version = "0.13.1", features = [
  "otlp",
  "tracing_subscriber_ext",
] }
opentelemetry = { version = "0.20.0", features = ["rt-tokio"] }
serde_json = "1.0.107"
tokio = { version = "1.32.0", features = ["full"] }
tracing = "0.1.37"
tracing-opentelemetry-instrumentation-sdk = "0.13.1"
```

Can you point out what am I doing wrong? What do i need to do so that the trace_id becomes the same?

Thank you.

**Comment by fhsgoncalves** [comment] 2023-09-19 17:24
I'm also experiencing a very similar behavior, but I'm exporting the traces to datadog.

The effect is the same:
![Screenshot 2023-09-19 at 14 22 45](https://github.com/davidB/tracing-opentelemetry-instrumentation-sdk/assets/8892624/bcfa76a8-87ae-4287-9f45-3d108f1fa94a)
In this picture, the trace `find_account` should have a parent span and be inside of resource `POST /account.lookup`, but it being reported as it own resource probably because this mismatch of trace_id.

**Comment by davidB** [comment] 2023-09-23 15:15
@rezmuh , I re-run the example 

- on 0.13.1, I can reproduce the error
- on 0.14.1 (& master) and I got the expected behavior (aka same trace_id, and 1 trace with 2 span in jaeger)

But it seems the crate was not released as expected. I'll republish 0.14.1

**Comment by davidB** [comment] 2023-09-23 16:37
@tsroka, which issue do you had with tracing-opentelemetry 0.21 ?

**Comment by tsroka** [comment] 2023-09-23 18:50
@davidB when i updated opentelemetry to 0.21 (but was still using axum-tracing 0.13.1) i did not see traceparent header in the http response, but did not investigate any further

**Comment by rezmuh** [comment] 2023-09-27 09:14
Hi @davidB I just updated your crate to `0.41.1` and keep opentelemetry crate to `0.20.0`. The problem is solved.

Thank you!

**Closed** 2023-09-27 10:12 UTC
